# Generated by Django 5.1.2 on 2024-10-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteiners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='Cliente Desconhecido', max_length=100)),
                ('numero_conteiner', models.CharField(max_length=11, unique=True)),
                ('tipo', models.CharField(choices=[('20', '20'), ('40', '40')], max_length=3)),
                ('status', models.CharField(choices=[('cheio', 'Cheio'), ('vazio', 'Vazio')], max_length=6)),
                ('categoria', models.CharField(choices=[('importação', 'Importação'), ('exportação', 'Exportação')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('embarque', 'Embarque'), ('desembarque', 'Desembarque'), ('gate in', 'Gate In'), ('gate out', 'Gate Out'), ('reposicionamento', 'Reposicionamento'), ('pesagem', 'Pesagem'), ('scanner', 'Scanner')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('conteiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteiners.conteiners')),
            ],
        ),
    ]
